  - name: create dummylander webroot
    file:
      path: "{{ dummypath }}{{ domains[0] }}/webroot/"
      state: directory

  - name: install nginx-config
    template:
      src: nginxconf/nginx.conf.deb{{ ansible_distribution_major_version }}.j2
      dest: "/etc/nginx/sites-available/dummylander-{{ domains[0] }}"
      owner: root
      group: root
      mode: 0644
    notify:
    - restart nginx

  - name: activate nginx dummylander config
    file:
      src: "/etc/nginx/sites-available/dummylander-{{ domains[0] }}"
      dest: "/etc/nginx/sites-enabled/dummylander-{{ domains[0] }}"
      state: link
    notify:
    - restart nginx
